---
- name: Create overcloud prep deployment script
  template:
    src: "{{ overcloud_prep_deployment_script }}"
    dest: "{{ working_dir }}/overcloud-prep-deployment.sh"
    mode: 0755

- name: Prepare the undercloud for overcloud deploy
  shell: |
    {{ working_dir }}/overcloud-prep-deployment.sh > \
    {{ overcloud_prep_deployment_log }} 2>&1

- name: Create network environment file for network isolation
  tags:
    - undercloud-scripts
  template:
    src: "{{ network_environment_file }}"
    dest: "{{ working_dir }}/network-environment.yaml"
    mode: 0755
  when: network_isolation

